### PR TITLE
Check if kcbt is set

### PR DESCRIPTION
**Pull request by cscribn**
Before submitting your PR (pull request), please check the following:
* [x] There is no other PR (open or closed) similar to yours. If there is, please first discuss over there.
* [x] Each commit messages follows the [Seven Rules of a Great Commit Message](https://cbea.ms/git-commit/#seven-rules).
* [x] Each commit message includes `Fixes #<bug>` or `Resolves #<issue>` in its body (not subject) for each issue it resolves (if any).
* [x] You have [squashed](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#_squashing) any redundant or insignificant commits.

### CODE REVIEW

**Comment by cscribn** [comment]
@marlonrichert anything I can do to help this be considered for merge?

**Comment by marlonrichert** [comment]
It looks fine to me. 👍🏽

**Comment by marlonrichert** [comment]
On second inspection, I do actually have some requests for changes. I'll add them as comments on your code.

**Comment by marlonrichert** [comment]
Merged as b223e73. Thanks!

**Pull request closed without merging**
