### PR TITLE
Delete breaking zstyle from OMZ

### LINKED ISSUE #483: Menu items not showing with OMZ
When I try using the suggestions, they do not appear at the bottom of the prompt. I always have to use the down arrow to bring them up. They seem to flicker when I press the tab key (unless there is only one obvious choice).
This used to work in Ubuntu 20.04 with the same Agnoster theme.

- [x] I have carefully read all of the instructions in this issue template.
- [x] I have carried them out to the letter.

Failure to do so can and will result in your issue being closed without warning.

## Environment
```zsh
print -l $_autocomplete__funcfiletrace
git -C ~zsh-autocomplete log --oneline -n1
```

```zsh
$ print $VENDOR $OSTYPE $SHELL $ZSH_ARGZERO $ZSH_PATCHLEVEL
ubuntu linux-gnu /usr/bin/zsh /usr/bin/zsh ubuntu/5.8.1-1

$ print -l $_autocomplete__funcfiletrace
/home/avneesh/.zshrc:82

$ git -C ~zsh-autocomplete log --oneline -n1
aed8e17 (HEAD -> main, origin/main, origin/HEAD) Fix recent-dirs naming conflict
```

* Operating system: Linux Mint 21 (Vanessa), downstream of Ubuntu 22.04 (Jammy) and Debian bookworm
* Terminal emulator: Terminator (version 2.1.1), ZSH, Agnoster theme

- [x] I have filled out the fields above.
- [x] I have ran the commands in the code block above.
- [x] I have pasted their output into the same block. 

## Steps to reproduce
```zsh
cd $(mktemp -d)
git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git
> .zshrc <<EOF
PS1='%# ' PS2= RPS2='%^'; setopt transientrprompt interactivecomments
source ~/zsh-autocomplete/zsh-autocomplete.plugin.zsh
EOF
env -i HOME=$PWD PATH=$PATH TERM=$TERM ${TERMINFO:+TERMINFO=$TERMINFO} zsh -d
```
- [x] I have run the code block above to create a test environment.
- [ ] I have reproduced my problem in this environment in the most minimal way possible.
- [ ] I have copy-pasted my entire test session into the same code block.

Somehow, in the above steps, the issue does not occur.

The problem is not getting options here
image

In the above test session, they do come up
image

### PR DESCRIPTION
**Pull request by marlonrichert**
Reverts part of 96bbb5bb5b3698ca23d54ee28eb595a3727bf6df. Fixes #483.

### CODE REVIEW

**Comment by MrAureliusR** [comment]
This essentially has the same effect as the other commit discussed in that issue -- it works for about 4-5 commands and then stops autocompleting.
I just did an [asciinema recording][1] of it. At various points (when I'm typing euler.py for example) I'm hitting TAB and nothing is happening. Then I show that sudo dkms does not show the options for dkms, but after re-sourcing ~/.zshrc it starts working again. What you can't see is that at certain points I'm hitting tab and getting a brief flash of the options on screen -- I guess asciinema doesn't record at a high enough "frame rate" for it to catch those brief glimpses. After re-sourcing .zshrc I actually had a hard time getting it to break the second time, but given enough commands it will always break, without fail.
This version does seem to be somewhat better, increasing from 3-4 commands to as many as 10 before it breaks, but again it's still acting strangely.

[1]: https://asciinema.org/a/1qvNfuRposILv2MeSj1Ie2UdO

**Comment by latipun7** [comment]
Cool, thanks @marlonrichert. This works for minimal OMZ + zsh-autocomplete. Also, it works for my complete ZSH setup :+1: 
I tried so many commands, not just 10 commands, & it still works great as expected.

**Comment by MrAureliusR** [comment]
> Cool, thanks @marlonrichert. This works for minimal OMZ + zsh-autocomplete. Also, it works for my complete ZSH setup +1 I tried so many commands, not just 10 commands, & it still works great as expected. Proof: https://asciinema.org/a/u8uzbOC48LOHtfdAK8kTzoCPR

I don't think you need to provide "proof" when things are working properly, lol.

Still having the same issues. Both this PR and the old commit function about the same. Really frustrating as I really love the functionality of zsh-autocomplete but I just can't use my shell if tab-completion breaks every few commands. It might have something to do with the term I'm using (kitty) but when I do the minimal reproduction setup, everything works fine (at least, the last time I tried it, it did). Maybe I'll try using a different terminal emulator and see if I get any different results.

**Comment by latipun7** [comment]
> > Cool, thanks @marlonrichert. This works for minimal OMZ + zsh-autocomplete. Also, it works for my complete ZSH setup +1 I tried so many commands, not just 10 commands, & it still works great as expected. Proof: https://asciinema.org/a/u8uzbOC48LOHtfdAK8kTzoCPR
> 
> I don't think you need to provide "proof" when things are working properly, lol.
> 
> It might have something to do with the term I'm using (kitty) but when I do the minimal reproduction setup, everything works fine (at least, the last time I tried it, it did). Maybe I'll try using a different terminal emulator and see if I get any different results.

No, I'm also using kitty, see the env on my cast above. It might something to do with your zsh configs. Plugins? Custom? Try your minimal and only OMZ

**Comment by marlonrichert** [comment]
> I don't think you need to provide "proof" when things are working properly, lol.

No, but they’re just trying to be helpful. No need to “lol” at them; that’s just bad manners.

**Comment by marlonrichert** [comment]
@MrAureliusR Your problem appears to be different than the other persons reporting in #483. Please open a new issue and carefully fill out the bug report template. Then we can try to figure out properly what’s causing you grief.

**Pull request merged**
