### PR TITLE
Fixed bindings if using iTerm2

### PR DESCRIPTION
**Pull request by Dwight-D**
Check if using iTerm2, if so use alternate arrow keybinds

### CODE REVIEW

**Comment by wookayin** [comment]
`$TERM_PROGRAM` might not be propagated if it is a remote machine over SSH. So rather than having a if-else statement, you should have two separate bindkey statements. (one for `^[OA` and one for `^[[A`, etc.)

**Comment by marlonrichert** [comment]
This is not iTerm2-specific. It depends on what keymap mode your terminal is in.
* If it's in normal mode (rmkx), the ↑ key will send `^[[A`.
* If it's in application mode (smkx), the ↑ key will send `^[[A`.
(See https://github.com/fish-shell/fish-shell/issues/2139 for further reading.)

`zsh4humans` has a decent fix for this: https://github.com/romkatv/zsh4humans/blob/v1/z4h.zsh#L746

**Comment by Dwight-D** [comment]
Ah, and just as I "fixed" it too. I think I will just change it to "UpAlternate" or something like that and bind both, that way the users don't have to change any of their bindings. Seems like a more precise fix with less potential side effects. What do you think?

**Comment by marlonrichert** [comment]
Better would be to rename the `^[[A` version to `CursorUp` and call the `^[OA` version `KeyUp`. That's what they're called in the terminfo db.

**Comment by Dwight-D** [comment]
Ok, how about this?

**Comment by marlonrichert** [comment]
Thanks, looks good. I will still change it a bit, though. 🙂

**Comment by marlonrichert** [comment]
Oh, and for future reference: I would prefer if you could squash all the changes into a single commit. But no need to bother with that now, since I will rewrite it anyway.

**Comment by Dwight-D** [comment]
Ah, of course. Gitlab auto-squash has spoiled me...

**Comment by marlonrichert** [comment]
@Dwight-D I updated the code. Can you test if it resolves the issue for you?

**Comment by Dwight-D** [comment]
@marlonrichert Yeah, thanks!

**Pull request closed without merging**
